name: Eurooppalaisten asenteista ja hyvinvoinnista
description: Something here
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: false
baseurl: https://okffi-science.github.io/avoin-suomi-2014
